Add idh jupyterhub slis
operate-first/operations pull request #115
Opened 2021-03-08 19:14 UTC by anishasthana

2021-03-08 19:46 UTC, hemajv requested changes

2021-03-08 19:46 UTC, hemajv commented on sli-slo/jupyterhub.md
> +| Status of Jupyterhub                        | Availability | Hub       | This expression reports the current availability status of jupyterhub master.
should we have a placeholder for the labels inside the `up` metric expression?

2021-03-08 19:46 UTC, hemajv commented on sli-slo/jupyterhub.md
> +| Notebook container creation errors          | Error        | Users     | This keeps a track of the errors encountered when spawning a notebook container.
I think there's a missing escape `\` character in the metric expression, due to which the entire expression is not being rendered in the markdown, it should be:

`count(kube\_pod\_container\_status\_waiting\_reason{pod=\~"jupyterhub-nb-.\*", reason=~"CrashLoopBackOff|ErrImagePull|ImagePullBackOff"} == 1) by(reason,pod)`

2021-03-08 19:46 UTC, hemajv commented on sli-slo/jupyterhub.md
> +| OOMKilled Jupyterhub Pods                   | Error        | Hub, DB   | Counts the number of pods that have been OOMKilled
same for this, the metric expression should be:

`avg by (pod) (sum\_over\_time(kube\_pod\_container\_status\_terminated\_reason{pod=\~"jupyterhub-\\\\d.\*-\\\\D\\\\D\\\\D\\\\D\\\\D|jupyterhub-db-\\\\d.\*", reason="OOMKilled"}\[1h\]))`

2021-03-08 19:46 UTC, hemajv commented on sli-slo/jupyterhub.md
> +| Jupyterhub Memory Usage                     | Saturation   | Hub,DB    | This measures the memory usage of key Jupyterhub pods over time
missing `\` character, metric expression should be updated to:

`sum(container\_memory\_rss{pod=\~"jupyterhub-\\\\d.\*|jupyterhub-db.\*"}) by (pod)`

2021-03-08 19:46 UTC, hemajv commented on sli-slo/jupyterhub.md
> +| Jupyterhub CPU usage                        | Saturation   | Hub,DB    | This measures the CPU usage of key Jupyterhub pods over time
missing `\` character, metric expression should be updated to:

`(sum(rate(container\_cpu\_usage\_seconds\_total{pod=\~"jupyterhub-\\\\d.\*|jupyterhub-db.\*"}\[5m\])) by (pod))\*100`

2021-03-08 19:46 UTC, hemajv commented on sli-slo/jupyterhub.md
> +| Jupyterhub Database PVC Usage               | Saturation   | DB        | This expression monitors the current consumption % of the DB PVC. If it hits 100% the DB pod will not start up and we are at
missing `\` character, metric expression should be updated to:

`(avg by (persistentvolumeclaim) (kubelet\_volume\_stats\_used\_bytes{persistentvolumeclaim=\~"jupyterhub-db"}))/(avg by (persistentvolumeclaim) (kubelet\_volume\_stats\_capacity\_bytes{persistentvolumeclaim=~"jupyterhub-db"}))`

2021-03-09 16:00 UTC, anishasthana commented on sli-slo/jupyterhub.md
> +| Status of Jupyterhub                        | Availability | Hub       | This expression reports the current availability status of jupyterhub master.
I didn't add any labels in as I wasn't quite certain what namespaces we'd want to look at. Internally we based it on `up{job="Jupyterhub Metrics"}`. What job are ya'll using to scrape jupyterhub metrics?

2021-03-09 16:03 UTC, anishasthana commented on sli-slo/jupyterhub.md
> +| Notebook container creation errors          | Error        | Users     | This keeps a track of the errors encountered when spawning a notebook container.
Turns out I actually had to add `\` right before the `|`s

2021-03-09 16:12 UTC, anishasthana commented
@hemajv updated the expressions, PTAL

2021-03-09 16:23 UTC, hemajv commented on sli-slo/jupyterhub.md
> +| Status of Jupyterhub                        | Availability | Hub       | This expression reports the current availability status of jupyterhub master.
ah gotcha! I think we just defined the expression based on the `service` label instead of `job`, like `up{service="jupyterhub"}`

2021-03-09 16:29 UTC, hemajv commented on sli-slo/jupyterhub.md
> +| Notebook container creation errors          | Error        | Users     | This keeps a track of the errors encountered when spawning a notebook container.
@anishasthana seems like its still appearing like so in the markdown:

![Screenshot from 2021-03-09 11-25-27](https://user-images.githubusercontent.com/7343099/110503567-51db2e80-80ca-11eb-8c14-2bc3403ea532.png)

so I think the `\` has to be placed before the `~` like `{pod=\~.....`}

2021-03-09 16:30 UTC, hemajv commented on sli-slo/jupyterhub.md
> +| Jupyterhub Database PVC Usage               | Saturation   | DB        | This expression monitors the current consumption % of the DB PVC. If it hits 100% the DB pod will not start up and we are at
same for this one, it appears like:
![Screenshot from 2021-03-09 11-25-38](https://user-images.githubusercontent.com/7343099/110504087-d037d080-80ca-11eb-9673-59a850106047.png)

so I think the `\` needs to be placed before `~`

2021-03-09 16:45 UTC, anishasthana commented on sli-slo/jupyterhub.md
> +| Notebook container creation errors          | Error        | Users     | This keeps a track of the errors encountered when spawning a notebook container.
That's interesting, my local render isn't showing that. I'll fix this

2021-03-09 16:49 UTC, anishasthana commented on sli-slo/jupyterhub.md
> +| Status of Jupyterhub                        | Availability | Hub       | This expression reports the current availability status of jupyterhub master.
Done

2021-03-09 16:49 UTC, anishasthana commented on sli-slo/jupyterhub.md
> +| Jupyterhub Database PVC Usage               | Saturation   | DB        | This expression monitors the current consumption % of the DB PVC. If it hits 100% the DB pod will not start up and we are at
Interesting, I think it's fixed now. Wonder why my local render was not showing that.

2021-03-09 16:55 UTC, hemajv approved these changes
lgtm! :ship:

2021-03-09 16:56 UTC, merged