Update README
operate-first/operations pull request #15
Opened 2020-11-05 20:55 UTC by hemajv

Adding more content to refine the README

2020-11-05 20:55 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign  after the PR has been reviewed.
You can assign the PR to them by writing `/assign ` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2FSRE).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/operate-first/SRE/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2020-11-06 13:13 UTC, anishasthana requested changes

2020-11-06 13:13 UTC, anishasthana commented on README.md
> +We have defined Service Level Indicators (SLI) and Service Level Objectives (SLO) for each of the ODH applications to help us monitor the availability of the service and improve its reliability.
We will eventually deploy non-ODH applications right? Should we change "for each of the ODH applications" to "SRE-managed Services" or something similar to that?

2020-11-06 13:13 UTC, anishasthana commented on README.md
> +For all the services being monitored, we have defined runbooks to provide information on how to administer, debug and effectively manage and troubleshoot common problems of a service.
` administer, debug and effectively manage and troubleshoot common` -> ` administer, debug, and effectively troubleshoot common problems of a service`

2020-11-06 13:13 UTC, anishasthana commented on README.md
> +We have the [Open Data Hub](https://opendatahub.io/) applications deployed and running in a MOC [(Mass Open Cloud)](https://massopen.cloud/) cluster. Open Data Hub is an end-to-end AI/ML platform on
remove the first `the`

2020-11-06 15:44 UTC, hemajv commented on README.md
> +For all the services being monitored, we have defined runbooks to provide information on how to administer, debug and effectively manage and troubleshoot common problems of a service.
fixed :+1:

2020-11-06 15:51 UTC, anishasthana approved these changes

2020-11-06 15:51 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/operate-first/SRE/pull/15#pullrequestreview-525276652" title="Approved">anishasthana</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign  after the PR has been reviewed.
You can assign the PR to them by writing `/assign ` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2FSRE).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/operate-first/SRE/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2020-11-06 15:51 UTC, HumairAK approved these changes

2020-11-06 15:51 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/operate-first/SRE/pull/15#pullrequestreview-525276652" title="Approved">anishasthana</a>*, *<a href="https://github.com/operate-first/SRE/pull/15#pullrequestreview-525277172" title="Approved">HumairAK</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign  after the PR has been reviewed.
You can assign the PR to them by writing `/assign ` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2FSRE).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/operate-first/SRE/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2020-11-06 15:54 UTC, merged