Add grafana dashboard for jupyterhub
operate-first/operations pull request #17
Opened 2020-11-11 21:42 UTC by hemajv

Adding an example monitoring dashboard for JupyterHub based on the defined [SLI/SLO](https://github.com/operate-first/SRE/blob/master/sli-slo/jupyterhub.md). You can preview the dashboard [here](https://grafana.datahub.redhat.com/dashboard/db/jupyterhub-sli-slo?orgId=1).

(This addresses #5)

2020-11-11 21:42 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign  after the PR has been reviewed.
You can assign the PR to them by writing `/assign ` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2FSRE).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/operate-first/SRE/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2020-11-13 17:27 UTC, anishasthana requested changes
As discussed offline, could we do the following?
1) Use Grafana 7.x to export the dashboard
2) Include a Grafana Dashboard object (the official CR utilized by the Grafana Operator)

2020-11-13 17:27 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **hemajv** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @hemajv` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2FSRE).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/operate-first/SRE/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["hemajv"]} -->

2020-11-17 22:39 UTC, anishasthana requested changes

2020-11-17 22:39 UTC, anishasthana commented on dashboards/jupyterhub-dashboard.yaml
> +          "version": "4.7.0-pre1"
wrong grafana version here?

2020-11-17 22:39 UTC, anishasthana commented on dashboards/jupyterhub-dashboard.yaml
> +      "version": 47
Wanna change the version to 1?

2020-12-14 18:55 UTC, hemajv commented on dashboards/jupyterhub-dashboard.yaml
> +          "version": "4.7.0-pre1"
fixed :+1:

2020-12-14 21:46 UTC, anishasthana requested changes

2020-12-14 21:46 UTC, anishasthana commented on dashboards/Jupyterhub-dashboard.json
> +          "expr": "count(count(container_cpu_usage_seconds_total{namespace=\"dh-prod-jupyterhub\",pod_name=~\".*jupyterhub-nb.*\"}) by(pod_name))",
This says `dh-prod-jupyterhub` I'm willing to bet we'll have at least a few other similar instances.

2020-12-14 22:22 UTC, 4n4nd commented
/retest

2020-12-14 22:23 UTC, sesheta commented
Hi @4n4nd
      Unauthorised to run /retest command.

2020-12-14 22:26 UTC, hemajv commented on dashboards/Jupyterhub-dashboard.json
> +          "expr": "count(count(container_cpu_usage_seconds_total{namespace=\"dh-prod-jupyterhub\",pod_name=~\".*jupyterhub-nb.*\"}) by(pod_name))",
good catch! :+1:  fixed it by creating a `variable` to filter on instead

2020-12-15 15:48 UTC, anishasthana commented on dashboards/Jupyterhub-dashboard.json
> +}
Missing newline? :-)
Could we also change the version to `1`?

2020-12-15 16:17 UTC, hemajv commented on dashboards/Jupyterhub-dashboard.json
> +}
umm exported the JSON from grafana itself, and it didn't have a newline
updated the version :+1:

2020-12-15 16:39 UTC, HumairAK approved these changes

2020-12-15 16:39 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/operate-first/SRE/pull/17#pullrequestreview-552651680" title="Approved">HumairAK</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2FSRE).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/operate-first/SRE/blob/master/OWNERS)~~ [HumairAK]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2020-12-15 16:42 UTC, anishasthana approved these changes

2020-12-15 16:42 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/operate-first/SRE/pull/17#pullrequestreview-552654438" title="Approved">anishasthana</a>*, *<a href="https://github.com/operate-first/SRE/pull/17#pullrequestreview-552651680" title="Approved">HumairAK</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2FSRE).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/operate-first/SRE/blob/master/OWNERS)~~ [HumairAK,anishasthana]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2020-12-15 16:43 UTC, merged

2020-12-15 16:43 UTC, 4n4nd commented
/retest

2020-12-15 16:44 UTC, sesheta commented
Hi @4n4nd
      Unauthorised to run /retest command.