Add incident management procedure
operate-first/operations pull request #231
Opened 2021-03-26 16:40 UTC by HumairAK

Resolve #226

Wasn't sure if this should go in runbooks or the incident-managent dock, I opted for the incident-management doc (don't hold a strong opinion either way here).

2021-03-26 16:41 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **humairak** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @humairak` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2FSRE).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/operate-first/SRE/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["humairak"]} -->

2021-03-29 10:41 UTC, tumido commented on incident-management/incident-management-procedure.md
> +2. CC should paste the same message in the slack [Announcement channel][4]
I don't think posting the same message on Slack is desired. Rather post a short summary with a link to the GH incident than the full blown issue template as shown below.

I'd rather see an message like this:

```
INCIDENT NOTICE: Zero cluster - JupyterHub outage, for details please follow [this] issue.
```

2021-03-29 10:41 UTC, tumido commented on incident-management/incident-management-procedure.md
> +```
```suggestion
```text
```

2021-03-29 13:36 UTC, HumairAK commented on incident-management/incident-management-procedure.md
> +2. CC should paste the same message in the slack [Announcement channel][4]
updated

2021-03-29 13:45 UTC, tumido reviewed
/lgtm

Thank you for this! :+1:

2021-03-29 14:03 UTC, larsks requested changes

2021-03-29 14:03 UTC, larsks commented on incident-management/incident-management-procedure.md
> +When a _significant_ update is first agreed upon, the communications coordinator must be identified.
Do we want to include guidelines w/r/t what constitutes "significant"? Or is this a "we'll know it when we see it" situation?

2021-03-29 14:03 UTC, larsks commented on incident-management/incident-management-procedure.md
> +<Optional: Any important information about lingering effects of the iWe should aim to confine all important information to a singular channel ncident>
There seems to have been an editing error in this paragraph.

2021-03-29 14:19 UTC, HumairAK commented on incident-management/incident-management-procedure.md
> +When a _significant_ update is first agreed upon, the communications coordinator must be identified.
I was thinking the latter, I didn't really have a well defined criteria in my head. What do you think?

2021-03-29 14:20 UTC, sesheta commented
New changes are detected. LGTM label has been removed.

2021-03-29 14:20 UTC, HumairAK commented on incident-management/incident-management-procedure.md
> +<Optional: Any important information about lingering effects of the iWe should aim to confine all important information to a singular channel ncident>
bah I think I pasted something from my clipboard accidentally, thanks!

2021-03-29 14:24 UTC, larsks commented on incident-management/incident-management-procedure.md
> +When a _significant_ update is first agreed upon, the communications coordinator must be identified.
My first inclination is to drop the word "significant" and have this procedure apply specifically to OpenShift upgrades (i.e., OCP version changes). We're performing a +0.0.2 upgrade right now and I guess it seems "significant" in that it's going to involve reboots of every node in the cluster.

Maybe the metric for "significant" is "requires reboots of the controller nodes", or maybe it's "requires reboots of any nodes" (e.g., a new or modified MachineConfig results in rolling reboots of the affected pool of nodes).

2021-03-29 14:46 UTC, HumairAK commented on incident-management/incident-management-procedure.md
> +When a _significant_ update is first agreed upon, the communications coordinator must be identified.
I could add a criteria for declaring an update like I did for incidents, some suggestions: 

For clusters: 
- Requires rebooting of any nodes 
- May result in disruption to cluster services (scheduling, network issues, auth, storage, etc.) for an extended period of time (> 5min).

For services (e.g. ODH): 
- May result in service downtime for an extended period of time (> 5min).

wdyt? 

+ @tumido

2021-03-29 14:51 UTC, hemajv commented on incident-management/incident-management-procedure.md
> +5. Send an announcement to the [Announcement channel][4] with a brief message and link to the Github issue thread.
should this be combined with Step 2? And should we also mention to send an email to `operate-first-users@lists.massopen.cloud`?

2021-03-29 14:55 UTC, hemajv commented on incident-management/incident-management-procedure.md
> +2. CC should paste the same message in the slack [Announcement channel][4]
are we planning to have a separate channel for communication during the incident? i.e. for all those involved in resolving the incident/upgrade (like how we had the incidents channel for idh)

2021-03-29 14:57 UTC, HumairAK commented on incident-management/incident-management-procedure.md
> +5. Send an announcement to the [Announcement channel][4] with a brief message and link to the Github issue thread.
> should this be combined with Step 2?  
ah the one in no. 5 is for the resolution announcement, I'll clarify. 

> And should we also mention to send an email to operate-first-users@lists.massopen.cloud? 

I wasn't sure about this, I felt like the announcement channel + issue is enough. I didn't want to add more non-OT work during an incident since our team is relatively small.

2021-03-29 15:00 UTC, tumido commented on incident-management/incident-management-procedure.md
> +2. CC should paste the same message in the slack [Announcement channel][4]
I don't think we should have too many channels. I think `#announcements` fits the role perfectly.

2021-03-29 15:02 UTC, tumido commented on incident-management/incident-management-procedure.md
> +When a _significant_ update is first agreed upon, the communications coordinator must be identified.
@HumairAK that sounds good to me. That's reasonable. I'd add for the services:

May result in restarting user workloads/rollouts - like JH servers

2021-03-29 17:14 UTC, HumairAK commented on incident-management/incident-management-procedure.md
> +When a _significant_ update is first agreed upon, the communications coordinator must be identified.
I've updated the above with a criteria, @larsks @tumido let me know what you think.

2021-03-29 17:15 UTC, HumairAK commented on incident-management/incident-management-procedure.md
> +5. Send an announcement to the [Announcement channel][4] with a brief message and link to the Github issue thread.
@hemajv I've clarified the 2nd announcement should be for a resolution message, let me know if that works.

2021-03-29 17:25 UTC, larsks commented on incident-management/incident-management-procedure.md
> +When a _significant_ update is first agreed upon, the communications coordinator must be identified.
@HumairAK I think that's better. I like that it's much more explicit.

2021-03-29 17:39 UTC, hemajv commented
/lgtm :+1:

2021-03-29 18:10 UTC, hemajv commented
/retest

2021-03-29 18:11 UTC, sesheta commented
<details>
<summary>Pre-Commit Test failed! Click here</summary>

```
[INFO] Initializing environment for git://github.com/Lucas-C/pre-commit-hooks.
[INFO] Initializing environment for git://github.com/pre-commit/pre-commit-hooks.
[INFO] Initializing environment for https://github.com/adrienverge/yamllint.git.
[INFO] Installing environment for git://github.com/Lucas-C/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for git://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/adrienverge/yamllint.git.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
Tabs remover.............................................................Passed
Trim Trailing Whitespace.................................................Failed
- hook id: trailing-whitespace
- exit code: 1
- files were modified by this hook

Fixing incident-management/incident-management-procedure.md

Check for merge conflicts................................................Passed
Fix End of Files.........................................................Passed
Check for added large files..............................................Passed
Check for case conflicts.................................................Passed
Check JSON...............................................................Passed
Check for broken symlinks............................(no files to check)Skipped
Detect Private Key.......................................................Passed
yamllint.................................................................Passed
```
</details>

2021-03-29 18:13 UTC, HumairAK commented
/retest

2021-03-30 08:52 UTC, tumido approved these changes
/approve

2021-03-30 08:52 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/operate-first/SRE/pull/231#pullrequestreview-624005897" title="Approved">tumido</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2FSRE).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/operate-first/SRE/blob/master/OWNERS)~~ [tumido]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2021-03-30 08:52 UTC, merged