Add JH runbooks
operate-first/operations pull request #232
Opened 2021-03-29 19:24 UTC by hemajv

Adding JH runbooks

(this is related to #218)

2021-03-29 19:24 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **hemajv** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @hemajv` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2FSRE).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/operate-first/SRE/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["hemajv"]} -->

2021-03-29 19:49 UTC, HumairAK commented
I see that you decided to break it up, I think I like it this way but we did add [this template](https://github.com/operate-first/SRE/blob/master/runbooks/jupyterhub.md), should we get rid of it? or use it as a 'table of contents' of sorts to organize links for the various parts?

2021-03-29 19:59 UTC, HumairAK commented on runbooks/jupyterhub/jupyterhub-customimages.md
> +## Adding custom images as Imagestream
Hrmm the info here seems similar to [this](https://github.com/aicoe-aiops/data-science-workflows/blob/master/docs/create_and_deploy_jh_image.md#adding-the-image-where-you-need-it) -- would it be better if we just link there instead of repeating the info?

2021-03-29 20:04 UTC, HumairAK commented on runbooks/jupyterhub/jupyterhub-customimages.md
> +## Why can't I see the custom image after adding it in the operate-first/apps/tree/master/odh/base/jupyterhub/notebook-images?
The title for this subsection is a bit hard to read, may I suggest changing this: 

```
## Why can't I see the custom image after adding it in the operate-first/apps/tree/master/odh/base/jupyterhub/notebook-images?
```
to: 

```text
## Custom Image not listed in Spawner UI

After adding the custom image to `odh/base/jupyterhub/notebook-images` if the images do not show up in the JH Spawner UI then ensure the following: 

- The imagestream has the label:   opendatahub.io/notebook-image: "true"
- The imagestream was deployed by ArgoCD in [this app](https://argocd-server-argocd.apps.moc-infra.massopen.cloud/applications/opf-jupyterhub).
```

2021-03-29 20:22 UTC, HumairAK commented on runbooks/jupyterhub/jupyterhub-pvcoutofspace.md
> +- <respective steps to be followed>
I don't think this bullet point is rendering as you intended (it wont' show up as it stands)

2021-03-29 20:37 UTC, HumairAK commented
So from my perspective I see 2 types of docs here: 

1 is there's a problem that needs to be solved: 
- jupyterhub-pvcoutofspace.md 
- jupyterhub-serviceisnolongeravailable.md 

2 seems more like a how-to doc: 
- jupyterhub-customnotebooksizes.md 
- jupyterhub-customimages.md

I think we should consider why we want a runbook, from the [SRE book](https://landing.google.com/sre/sre-book/chapters/introduction/): 
> “clear and thorough troubleshooting steps and tips are valuable when responding to a high-stakes or time-sensitive page.”

I think this is accomplished with the first 2 but not the second 2. I think if we can convert the second 2 to adhere to the template of the first. Or we can simply move these to be under the `docs` folder in the `apps` repo and link to them from here. More generally, I think we should draw a clear distinction on what should go in the `docs` folder in the other repos vs what goes in the `runbooks` here, otherwise it could become unclear where to look for information.

2021-03-29 20:50 UTC, hemajv commented on runbooks/jupyterhub/jupyterhub-pvcoutofspace.md
> +- <respective steps to be followed>
oh so I was hoping someone could tell me what the exact steps are to be followed to resize someone's PVC as I was unsure :sweat_smile:

2021-03-29 20:53 UTC, hemajv commented
> So from my perspective I see 2 types of docs here:
> 
> 1 is there's a problem that needs to be solved:
> 
> * jupyterhub-pvcoutofspace.md
> * jupyterhub-serviceisnolongeravailable.md
> 
> 2 seems more like a how-to doc:
> 
> * jupyterhub-customnotebooksizes.md
> * jupyterhub-customimages.md
> 
> I think we should consider why we want a runbook, from the [SRE book](https://landing.google.com/sre/sre-book/chapters/introduction/):
> 
> > “clear and thorough troubleshooting steps and tips are valuable when responding to a high-stakes or time-sensitive page.”
> 
> I think this is accomplished with the first 2 but not the second 2. I think if we can convert the second 2 to adhere to the template of the first. Or we can simply move these to be under the `docs` folder in the `apps` repo and link to them from here. More generally, I think we should draw a clear distinction on what should go in the `docs` folder in the other repos vs what goes in the `runbooks` here, otherwise it could become unclear where to look for information.

Yes, I was a little confused as well. In my opinion, our runbooks should address the steps to be followed for resolving commonly occurring issues. So yes, thinks like jupyterhub pvc resizing, service unavailability and pods being stuck should have respective runbooks. If you think the ones listed under 2 are not needed, we can move them somewhere else

2021-03-30 09:37 UTC, tumido requested changes

2021-03-30 09:37 UTC, tumido commented on runbooks/jupyterhub/jupyterhub-pvcoutofspace.md
> +- <respective steps to be followed>
We already have a runbook of sort for Ops for this:

https://github.com/operate-first/blueprint/blob/main/docs/userstories/ops/increase_pvc_size_jh.feature

And for user as well:

https://github.com/operate-first/blueprint/blob/main/docs/userstories/jupyterhub-user/increase_pvc_size_jh.feature

Please don't duplicate the docs.

2021-03-30 09:37 UTC, tumido commented on runbooks/jupyterhub/jupyterhub-customimages.md
> +## Adding custom images as Imagestream
+ we also have an user story for Ops (sort of a runbook) for this:
https://github.com/operate-first/blueprint/blob/main/docs/userstories/ops/add_imagestream_to_jh.feature

let's not triple the docs here.

2021-03-30 09:37 UTC, tumido commented on runbooks/jupyterhub/jupyterhub-pvcoutofspace.md
> +view the dashboard at: https://grafana-route-opf-monitoring.apps.zero.massopen.cloud/d/YuYfkHYMk/jupyterhub-usage?orgId=1
We already have this defined here:

https://github.com/operate-first/blueprint/blob/main/docs/userstories/jupyterhub-user/analyze_storage.feature

2021-03-30 11:56 UTC, anishasthana commented
I think redirecting to links for existing docs would make sense,where they exist. It's okay if the runbook is basically "just" a link

2021-03-30 16:38 UTC, hemajv commented
@HumairAK @tumido I have updated to include just one runbook listing out commonly encountered problems with JH, pointing to relevant docs (where possible) and steps to fix them.

2021-03-30 16:59 UTC, 4n4nd reviewed
/lgtm

2021-03-30 17:52 UTC, HumairAK commented on runbooks/jupyterhub.md
> +User our [grafana dashboard](https://grafana-route-opf-monitoring.apps.zero.massopen.cloud/d/YuYfkHYMk/jupyterhub-usage?orgId=1) to determine if the user has, in fact, used up
change `User our` to: `Use our`

2021-03-30 17:59 UTC, HumairAK commented
I definitely like this version of the runbook much more @hemajv ++ 
other than that, there's just the comment above 
/lgtm

2021-03-30 19:42 UTC, sesheta commented
New changes are detected. LGTM label has been removed.

2021-03-31 09:33 UTC, tumido approved these changes
Thank you @hemajv ! This is really polished, I like it!

/lgtm
/approve

2021-03-31 09:33 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/operate-first/SRE/pull/232#pullrequestreview-625086152" title="Approved">tumido</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2FSRE).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/operate-first/SRE/blob/master/OWNERS)~~ [tumido]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2021-03-31 09:35 UTC, merged