Add Kafka runbook
operate-first/operations pull request #233
Opened 2021-03-29 20:49 UTC by hemajv

Runbook for Kafka

(this addresses #218)

2021-03-29 20:49 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **hemajv** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @hemajv` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2FSRE).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/operate-first/SRE/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["hemajv"]} -->

2021-03-30 09:31 UTC, tumido requested changes

2021-03-30 09:31 UTC, tumido commented on runbooks/kafka.md
> +| Node Type | Description |
`pod != node != deployment` in Kubernetes. I think we need to keep the terminology consistent. It should be either all called `pods` or `deployments + statefulsets`.

2021-03-30 09:31 UTC, tumido commented on runbooks/kafka.md
> +| Strimzi cluster operator | This is the main Strimzi operator pod. It orchestrates all other pods. |
It's a deployment and lives in a completely different namespace. It should be noted that this lives in `openshift-operators` namespace.

2021-03-30 09:31 UTC, tumido commented on runbooks/kafka.md
> +| Kafka Consumer Monitor | This is a custom deployment not managed by Strimzi. We use it to monitor Kafka consumer lag. |
We don't deploy a consumer monitor

2021-03-30 09:31 UTC, tumido commented on runbooks/kafka.md
> +If we need to escalate an issue with the <> team, instructions for doing so can be found at .
Please file an issue for the escalation procedure and link to it in here - we can't leave this blank.

2021-03-30 14:29 UTC, HumairAK commented on runbooks/kafka.md
> +If we need to escalate an issue with the <> team, instructions for doing so can be found at .
Hrmm we don't really have someone we can escalate kafka issues to. This runbook is for us, so the only "escalation" we can do is just reach out to someone else to come save us. I'm down to just get rid of escalation, and instead replace it with "People to contact for additional help." I'm thinking things like, strimzi team, Maulik from idh, etc.

2021-03-30 14:36 UTC, HumairAK commented on runbooks/kafka.md
> +| Strimzi cluster operator | This is the main Strimzi operator pod. It orchestrates all other pods. |
I think we can go a step further and just give the links to these locations to these pods/sts: 
e.g: 

| [Strimzi cluster operator][1] |  `<description>` 
| [Zookeeper][2]| `<description>` 

[1]: https://console-openshift-console.apps.zero.massopen.cloud/k8s/ns/openshift-operators/pods/strimzi-cluster-operator-v0.19.0-7c78d4cc-m654p
[2]: https://console-openshift-console.apps.zero.massopen.cloud/k8s/ns/opf-kafka/statefulsets/odh-message-bus-zookeeper

and note that you need cluster admin to access `openshift-operators` and need to be in the `operate-first` ocp group to access `opf-kafka` namespace.

2021-03-30 14:42 UTC, HumairAK commented on runbooks/kafka.md
> +| Kafka consumer group lag | The delay in message consumption for a particular consumer group | Close to zero, or not rising | Check consumers for a specific consumer group (typically [kafka2es](KAFK
do we have a panel for this?? I don't see it ;'( 

If not, let's take it out?

2021-03-30 14:45 UTC, HumairAK commented
@maulikjs  -- wondering if you could give this a look over? it needs to be generalized for our kafka deployment via odh: 

https://console-openshift-console.apps.zero.massopen.cloud/k8s/ns/opf-kafka/pods

2021-03-30 14:48 UTC, hemajv commented on runbooks/kafka.md
> +If we need to escalate an issue with the <> team, instructions for doing so can be found at .
sure, I can update that

2021-03-30 14:54 UTC, maulikjs commented on runbooks/kafka.md
> +| Zookeeper | Zookeeper pods. These are deployed by the Strimzi operator. The Kafka brokers connect to the zookeeper cluster to store important cluster information. |
I'd say, "zookeper performs controller election, cluster membership and maintain a list of all topics and configurations for the kafka brokers."

2021-03-30 14:59 UTC, maulikjs commented on runbooks/kafka.md
> +| Kafka Brokers | The Kafka broker pods that handle the Kafka message passing and storage. These are deployed and managed by the Strimzi Operator. |
Kafka brokers handle and store the topic log partitions and services the consumers and producers.

2021-03-30 15:03 UTC, maulikjs commented on runbooks/kafka.md
> +| Kafka Connect | These pods run kafka connectors. They connect to the Kafka brokers and perform specialized message passing functions. We do not use Kafka Connect for production workflows. These are
Kafka connect utilizes various connectors to connect the Kafka cluster to a variety of data sources and streams

2021-03-30 15:05 UTC, maulikjs commented on runbooks/kafka.md
> +
./kafka-log-dirs.sh 
This tool helps to query log directory usage on the specified brokers.

Even this is an important one

2021-03-30 15:06 UTC, maulikjs commented on runbooks/kafka.md
> +/opt/kafka/bin/kafka-consumer-groups.sh --bootstrap-server three-kafka-bootstrap:9092 --descibe --group $NAME
typo s/descibe/describe

2021-03-30 15:07 UTC, maulikjs commented on runbooks/kafka.md
> +| Offline partitions count | The number of kafka partitions that aren't available | 0 | Check for offline Kafka brokers. Check for kafka topics that don't have replication fully enabled. |
No of kafka partitions that dont have any replicas online

2021-03-30 15:10 UTC, maulikjs commented on runbooks/kafka.md
> +### Topic partition reassignment
You will also need to use this command to decrease the replication factor sometimes.

2021-03-30 17:25 UTC, hemajv commented on runbooks/kafka.md
> +If we need to escalate an issue with the <> team, instructions for doing so can be found at .
do we know an email/chat channel for Strimzi team that we could mention?

2021-03-30 17:28 UTC, hemajv commented on runbooks/kafka.md
> +### Topic partition reassignment
added changes! thanks for the inputs @maulikjs :smile:

2021-03-30 17:34 UTC, 4n4nd commented on runbooks/kafka.md
> +| Kafka Connect] | Kafka connect utilizes various connectors to connect the Kafka cluster to a variety of data sources and streams. These are deployed and managed by the Strimzi Operator. |
stray character `]`

2021-03-30 17:56 UTC, maulikjs commented on runbooks/kafka.md
> +### Topic partition reassignment
My pleasure :D

2021-03-30 17:57 UTC, maulikjs commented on runbooks/kafka.md
> +If we need to escalate an issue with the <> team, instructions for doing so can be found at .
https://strimzi.io/community/

2021-03-30 18:01 UTC, HumairAK commented on runbooks/kafka.md
> +* Strimzi Team -
did you mean to add links here? (assuming so because of the `-`)

2021-03-30 18:03 UTC, hemajv commented on runbooks/kafka.md
> +* Strimzi Team -
yes, do we have an email id or link to a chat channel maybe?

2021-03-30 18:19 UTC, HumairAK commented on runbooks/kafka.md
> +* Strimzi Team -
Looks like @maulikjs 's link above has  chatroom link for slack: https://slack.cncf.io/

2021-03-30 18:19 UTC, HumairAK commented on runbooks/kafka.md
> +* Strimzi Team -
I don't see very many channels in there though...

2021-03-30 19:29 UTC, HumairAK commented
/lgtm

2021-03-30 19:56 UTC, maulikjs commented on runbooks/kafka.md
> +| Under replicated partitions | The number of kafka partitions that don't have replication fully in sync | 0 | Check kafka broker pod logs for signs of errors |
s/replications/replicas

2021-03-30 19:56 UTC, maulikjs commented
Other than the 1 comment /lgtm

2021-03-30 20:04 UTC, sesheta commented
New changes are detected. LGTM label has been removed.

2021-03-30 20:08 UTC, maulikjs commented
/lgtm

2021-03-31 09:36 UTC, tumido reviewed
/lgtm
Thank you! This is nice :+1:

2021-03-31 13:19 UTC, HumairAK commented
/approve

2021-03-31 13:19 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/operate-first/SRE/pull/233#issuecomment-811061483" title="Approved">HumairAK</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2FSRE).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/operate-first/SRE/blob/master/OWNERS)~~ [HumairAK]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2021-03-31 14:51 UTC, merged