update prose for website
operate-first/operations pull request #397
Opened 2021-10-01 21:09 UTC by isabelizimm

2021-10-01 21:09 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **hemajv** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @hemajv` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2FSRE).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/operate-first/SRE/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["hemajv"]} -->

2021-10-05 12:22 UTC, isabelizimm commented
/assign @schwesig

2021-10-05 12:38 UTC, schwesig commented
3 Links are not working correctly (old cluster ?!)

1. http://prometheus-portal-opf-monitoring.apps.zero.massopen.cloud/graph/
2. https://grafana-route-opf-monitoring.apps.zero.massopen.cloud/
3. http://jupyterhub-opf-jupyterhub.apps.zero.massopen.cloud/hub/login

2021-10-05 12:46 UTC, schwesig commented on README.md
> -* [Prometheus](http://prometheus-portal-opf-monitoring.apps.zero.massopen.cloud/graph) - Monitoring tool capturing time series metrics for available Operate First services
Link is not working

2021-10-05 12:49 UTC, schwesig commented on sli-slo/tools.md
> +* [Prometheus](http://prometheus-portal-opf-monitoring.apps.zero.massopen.cloud/graph) - Monitoring tool capturing time series metrics for available Operate First services
Link is not working: old cluster?
Change Link.

2021-10-05 12:49 UTC, schwesig commented on README.md
> -* [Grafana](https://grafana-route-opf-monitoring.apps.zero.massopen.cloud/) - Visualization tool for creating monitoring dashboards
Link is not working: old cluster?
Change Link.

2021-10-05 12:50 UTC, schwesig commented on sli-slo/tools.md
> +* [Grafana](https://grafana-route-opf-monitoring.apps.zero.massopen.cloud/) - Visualization tool for creating monitoring dashboards
Link is not working: old cluster?
Change Link.

2021-10-05 12:50 UTC, schwesig commented on README.md
> -* [JupyterHub](https://jupyterhub-opf-jupyterhub.apps.zero.massopen.cloud/hub/login)
Link is not working: old cluster?
Change Link.

2021-10-05 12:50 UTC, schwesig commented on sli-slo/tools.md
> +* [JupyterHub](https://jupyterhub-opf-jupyterhub.apps.zero.massopen.cloud/hub/login)
Link is not working: old cluster?
Change Link.

2021-10-05 13:51 UTC, hemajv requested changes

2021-10-05 13:51 UTC, hemajv commented on README.md
> +1. Follow this link to find beginner-friendly issues [beginner friendly issues](https://github.com/operate-first/support/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22).
"beginner friendly issues" mentioned twice, remove and link to just one?

2021-10-05 13:51 UTC, hemajv commented on sli-slo/tools.md
> +* [JupyterHub](https://jupyterhub-opf-jupyterhub.apps.smaug.na.operate-first.cloud/login)
Do we want to add a short description to what JupyterHub is? and also maybe point to some resource on the Operate First website?

2021-10-05 13:51 UTC, hemajv commented on README.md
> +To learn more, check out the [incident management procedures](./incident-management/incident-management-procedure.md), [GitHub receiver setup](./incident-management/github-receiver-setup.md), learn t
Link all the resources to the Operate First website instead?

- https://www.operate-first.cloud/operations/sre/incident-management/incident-management-procedure.md
- https://www.operate-first.cloud/operations/sre/incident-management/github-receiver-setup.md
- https://www.operate-first.cloud/operations/sre/incident-management/configure-prometheus-alerts.md

2021-10-05 13:51 UTC, hemajv commented on README.md
> +If you'd like to learn SRE practices, but aren't sure where to start, let us help!
maybe we can update it to "If you'd like to learn and get hands on experience with SRE practices, but aren't sure where or how to start, let us help!"?

2021-10-05 15:51 UTC, schwesig approved these changes

2021-10-05 15:51 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/operate-first/SRE/pull/397#pullrequestreview-771636861" title="Approved">schwesig</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **hemajv** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @hemajv` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2FSRE).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/operate-first/SRE/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["hemajv"]} -->

2021-10-05 16:45 UTC, hemajv approved these changes

2021-10-05 16:45 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/operate-first/SRE/pull/397#pullrequestreview-771697641" title="Approved">hemajv</a>*, *<a href="https://github.com/operate-first/SRE/pull/397#pullrequestreview-771636861" title="Approved">schwesig</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2FSRE).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/operate-first/SRE/blob/master/OWNERS)~~ [hemajv]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2021-10-05 16:47 UTC, merged